wandb_version: 1

dataset:
  desc: null
  value: ACDC
model:
  desc: null
  value: UNet
loss function:
  desc: null
  value: DiceLoss
optimizer:
  desc: null
  value: Adam
learning rate:
  desc: null
  value: 0.001
transform:
  desc: null
  value:
  - <__main__.LoadData object at 0x000001F97DC99A10>
  - <__main__.HistogramEqualization object at 0x000001F967CA1ED0>
  - <monai.transforms.spatial.dictionary.RandRotated object at 0x000001F97D2A55D0>
  - <monai.transforms.spatial.dictionary.RandFlipd object at 0x000001FA7E5E9F90>
  - <monai.transforms.croppad.dictionary.RandSpatialCropd object at 0x000001F97DA5E690>
  - <monai.transforms.utility.dictionary.ToTensord object at 0x000001F967CB8850>
batch size:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716905575
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 48
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 48
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
