wandb_version: 1

dataset:
  desc: null
  value: ACDC
model:
  desc: null
  value: UNet
loss function:
  desc: null
  value: DiceLoss
optimizer:
  desc: null
  value: Adam
learning rate:
  desc: null
  value: 0.001
transform:
  desc: null
  value:
  - <__main__.LoadData object at 0x000002239BA683D0>
  - <__main__.HistogramEqualization object at 0x000002249AD23C10>
  - <monai.transforms.spatial.dictionary.RandRotated object at 0x000002249AD2E3D0>
  - <monai.transforms.spatial.dictionary.RandFlipd object at 0x000002249A40B410>
  - <monai.transforms.croppad.dictionary.RandSpatialCropd object at 0x00000223C145F750>
  - <monai.transforms.utility.dictionary.ToTensord object at 0x00000224577637D0>
batch size:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716904743
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 48
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 48
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
